name: C++ CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure CMake
      # This creates the build directory and prepares the project
      run: cmake -S . -B build

    - name: Build Project
      # This compiles your library and the tests
      run: cmake --build build

    - name: Run Unit Tests
      # This executes the tests and fails the build if any test fails
      run: cd build && ctest --output-on-failure

    - name: Configure CMake with ASan
      # -fsanitize=address finds memory leaks and buffer overflows
      run: cmake -S . -B build -DCMAKE_CXX_FLAGS="-fsanitize=address"

    - name: Build and Run with ASan
      run: |
        cmake --build build
        cd build && ctest --output-on-failure

    - name: Generate Coverage Report
      run: |
        sudo apt-get install lcov
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
        lcov --list coverage.info # This prints the % in the console
